- name: CI VM
  hosts: vm
  roles:
    - vm

- name: Init Ubuntu
  hosts: ubuntu
  roles:
    - ubuntu
    - role: ntp_client
      main_ntp_server: 192.168.1.1
      fallback_ntp_server: 192.168.1.2
      timezone: Europe/Moscow

- name: Vault Server
  hosts: hc_vault
  roles:
    - role: proxy_client
      set_http_proxy_env: true
      set_apt_proxy: true
      http_proxy: 192.168.1.8:3128
    - hc_vault

- name: Portainer Server
  hosts: portainer_server
  roles:
    - apt_upgrade
    - docker
    - portainer_server

- name: Utils Server
  hosts: utils_server
  roles:
    - utils_server
