- name: Common Tasks
  hosts: all
  roles:
    - role: ntp_client
      main_ntp_server: 192.168.1.1
      fallback_ntp_server: 192.168.1.2
      timezone: Europe/Moscow

- name: CI VM
  hosts: vm
  roles:
    - vm
  tags:
    - vm

- name: Vault Server
  hosts: hc_vault
  roles:
    - role: proxy_client
      set_http_proxy_env: true
      set_apt_proxy: true
      http_proxy: 192.168.1.8:3128
    - hc_vault
  tags:
    - hc_vault

- name: Portainer Server
  hosts: portainer_server
  roles:
    - apt_upgrade
    - docker
    - portainer_server
  tags:
    - portainer_server

- name: HQ Server
  hosts: hq_server
  roles:
    - hq_server
    - proxy_client
    - ansible_controller
    - terraform_controller
  tags:
    - utils_server

- name: SS Proxy Server
  hosts: ss_proxy
  roles:
    - sslocal_proxy_server
  tags:
    - ss_proxy
