ss_version: v1.17.2
ss_arch: x86_64-unknown-linux-gnu
v2ray_version: v1.3.2
v2ray_arch: linux-amd64
ssproxy_service_template: ../templates/ssproxy.service.j2
nofile: 51200

proxies:
  - proxy_type: http
    proxy_port: 3128
    ss_sip002_uri: "ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpiZDc5YzljNC1mZDYzLTRlNTctYWEwNS00OTdkYmQ0MTNiMTM@p01--rusty-spaghetty--ppp--gqb8-r4wz.code.run:443/?plugin=v2ray;path=/42f4e7a4-2dd7-44e8-a52c-467e81ea4007;host=p01--rusty-spaghetty--ppp--gqb8-r4wz.code.run;tls"
    sslocal_params: --protocol http
  - proxy_type: socks
    proxy_port: 1080
    ss_sip002_uri: "ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpiZDc5YzljNC1mZDYzLTRlNTctYWEwNS00OTdkYmQ0MTNiMTM@p01--rusty-spaghetty--ppp--gqb8-r4wz.code.run:443/?plugin=v2ray;path=/42f4e7a4-2dd7-44e8-a52c-467e81ea4007;host=p01--rusty-spaghetty--ppp--gqb8-r4wz.code.run;tls"
    sslocal_params: ""

limits:
  - key: "root soft nofile"
    value: "{{ nofile }}"
  - key: "root hard nofile"
    value: "{{ nofile }}"

sysctl_params:
  - key: fs.file-max
    value: "{{ nofile }}"
  - key: net.core.rmem_max
    value: 67108864
  - key: net.core.wmem_max
    value: 67108864
  - key: net.core.netdev_max_backlog
    value: 250000
  - key: net.core.somaxconn
    value: 4096
  - key: net.ipv4.tcp_syncookies
    value: 1
  - key: net.ipv4.tcp_tw_reuse
    value: 1
  # - key: net.ipv4.tcp_tw_recycle
  #   value: 0
  - key: net.ipv4.tcp_fin_timeout
    value: 30
  - key: net.ipv4.tcp_keepalive_time
    value: 1200
  - key: net.ipv4.ip_local_port_range
    value: 10000 65000
  - key: net.ipv4.tcp_max_syn_backlog
    value: 8192
  - key: net.ipv4.tcp_max_tw_buckets
    value: 5000
  - key: net.ipv4.tcp_fastopen
    value: 3
  - key: net.ipv4.tcp_mem
    value: 25600 51200 102400
  - key: net.ipv4.tcp_rmem
    value: 4096 87380 67108864
  - key: net.ipv4.tcp_wmem
    value: 4096 65536 67108864
  - key: net.ipv4.tcp_mtu_probing
    value: 1
  - key: net.ipv4.tcp_congestion_control
    value: hybla
