- name: Create a Portainer volume
  community.general.docker_volume:
    name: portainer_data

- name: Run a Portainer container
  community.general.docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    state: started
    restart_policy: always
    published_ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
